### ISSUE TITLE
SirMordred did not install with Python 3.9 (but did with Python 3.8)

### ISSUE THREAD

**Issue by lbergmans** [chaoss/grimoirelab-sirmordred#567]
_summary:_ While trying to install sirmordred, the installation of Pandas failed, using Python 3.8 instead of 3.9 solved the problem. I could not find any requirement about the Python version to be used.

A bit more detail:
* I got the following error while installing pandas (NB: 0.25.3 is quite old..):
```
    Exception: Cython-generated file 'pandas/_libs/algos.c' not found.
                     Cython is required to compile pandas from a development branch.
                     Please install Cython or download a release package of pandas.

```
* I was using PyCharm, so I tried to install using pip on the command line —> same issue.
* It appears there is no pre-built version (wheel) for Mac OSX 12.4 for the version of pandas that sirmordred needs (only `pandas-0.25.3-cp38-cp38-macosx_10_9_x86_64.whl`)
* Installed Cython (to compile locallly): that also resulted in an error:
```
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/src/ujson/python -Ipandas/_libs/src/ujson/lib -Ipandas/_libs/src/datetime -I/Users/lodewijk/git/grimoirelab_dev/sources/grimoirelab-sirmordred/venv/lib/python3.9/site-packages/numpy/core/include -I/Users/lodewijk/git/grimoirelab_dev/sources/grimoirelab-sirmordred/venv/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pandas/_libs/src/ujson/python/objToJSON.c -o build/temp.macosx-10.9-x86_64-3.9/pandas/_libs/src/ujson/python/objToJSON.o -D_GNU_SOURCE -Wno-unused-function
    pandas/_libs/src/ujson/python/objToJSON.c:181:12: error: use of undeclared identifier 'NUMPY_IMPORT_ARRAY_RETVAL'
        return NUMPY_IMPORT_ARRAY_RETVAL;
               ^
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
```
 As I mentioned: using Python 3.8 I could just install pandas without an issue

**Comment by jjmerchante** [comment]
Hi @lbergmans, SirMordred currently only works with Python 3.7 and Python 3.8. As you mention, there are some incompatibilities with the version of Pandas.

Thank you for reporting the issue.

**Comment by lbergmans** [comment]
I did not see that in the installation instructions, it would be good to add (not sure what the right place is)?

**Comment by jjmerchante** [comment]
Yes, maybe a new element in the requirements section in https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md could be a good place.

**Comment by ME-Msc** [comment]
Hi @jjmerchante , maybe it's good for new comers to get start with ubuntu20.04, which has python3.8 originaly. 
Because I have met a lot of problems to get start with ubuntu16/18 which needs to change the python version.
I hope the new element in requirements section could tell the new comers to use ubuntu20.04 for a smooth start!
Thank you.

**Comment by jjmerchante** [comment]
We [added Python 3.9, 3.10, and 3.11 support](https://github.com/chaoss/grimoirelab-sirmordred/pull/595). It will be available in the next release.
